/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: businessyuen (https://sketchfab.com/businessyuen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1400-boeing-737-airplane-for-free-f39ca33a81f14613a3d562d6b74c466a
Title: 1/400 Boeing 737 Airplane For Free
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Airplane(props) {
  const { nodes, materials } = useGLTF('/plane.glb')
  return (
    <group {...props} dispose={null} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Material_metal}
        scale={0.15}  
        position={[0,-2,0]}
        rotation={[0,-29.9, 0]}
      />
    </group>
  )
}

useGLTF.preload('/plane.glb')


